server:
  port: "3000"
  http_enabled: true
  webdav_enabled: true
  ftp_enabled: false
  ftp_port: 21
  sftp_enabled: false
  sftp_port: 22
database:
  url: dist/data/cohesion_dev.db
  user: test
  password: test
  dbname: cohesion